modLoader="javafml"
loaderVersion="[36,)"
license="GPL-3.0"
[[mods]]
modId="kelpcraft"
version="${file.jarVersion}"
displayName="Kelp Craft"
logoFile="kc.png"
credits="Thanks for this example mod goes to Java"
authors="GossChinese of Zeta Committee"
description='''
Add some tools made of kelp.
'''

[[dependencies.kelpcraft]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.kelpcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
